internal/command/put.go, internal/command/root_put_test.go, internal/command/root_test.go
=> Add - as an alias for stdin/stdout in the --file and --output flags

README.md, internal/command/put.go, internal/command/put_bool.go, internal/command/put_int.go, internal/command/put_object_internal.go, internal/command/put_string.go, internal/command/root_put_test.go, internal/command/root_select_test.go, internal/command/select.go
=> Make the selector flag optional. Fallback to first argument

README.md, go.mod, go.sum, internal/command/root_put_test.go, internal/command/root_select_test.go, internal/command/root_test.go, internal/storage/parser.go, internal/storage/xml.go, internal/storage/xml_test.go, tests/assets/example.xml
=> Support XML data format

README.md, internal/command/root_select_test.go, internal/command/select.go, internal/command/select_internal_test.go, internal/storage/json.go, internal/storage/json_test.go, internal/storage/parser.go, internal/storage/parser_test.go, internal/storage/toml.go, internal/storage/xml.go, internal/storage/xml_test.go
=> Format select command output correctly

README.md, internal/command/put.go, internal/command/put_object_internal.go, internal/command/select.go, node.go
=> Add a new --plain flag to avoid formatting select output

README.md, condition.go, dynamic_parser.go, internal/command/root_select_test.go, node.go
=> Sub selector

README.md, internal/command/root_put_test.go, internal/command/root_select_test.go, internal/storage/csv.go, internal/storage/csv_test.go, internal/storage/parser.go
=> Add CSV Parser

README.md, error.go, error_test.go, internal/command/put.go, internal/command/put_object_internal.go, internal/command/put_object_internal_test.go, internal/command/root_put_test.go, internal/command/root_select_test.go, internal/command/root_test.go, internal/command/select.go, internal/command/select_internal_test.go, internal/storage/csv.go, internal/storage/parser_test.go, internal/storage/xml_test.go, internal/storage/yaml_test.go, node.go, node_put.go, node_query.go, node_query_internal_test.go, node_query_multiple.go, node_query_multiple_internal_test.go, node_test.go
Closes #15 
Adds `QueryMultiple` and `PutMultiple` to a `Node`.
These new functions return/handle *all* found values, rather than the first.
It also adds a new index selector of `*`... this will select all the items in a list.
=> Add multi value selector.

dynamic_parser.go, internal/command/root_select_test.go, node.go
Closes #35 
Caused by a regex pattern matching too many sets of brackets
=> Fix an issue with dynamic selectors.

README.md, internal/command/root_put_test.go, internal/command/root_select_test.go, node.go, node_put.go, selector.go, selector_test.go
Allow escape characters in selectors.
=> Escape selectors

.github/workflows/test.yaml, README.md, condition.go, condition_equal.go, condition_key_equal.go, condition_test.go, internal/command/put_internal_test.go, internal/command/root_put_test.go, internal/command/root_select_test.go, node.go, node_put.go, node_query_multiple.go, node_test.go
=> Search selector

README.md, internal/command/put.go, internal/command/put_internal_test.go, internal/command/put_object_internal.go, internal/command/select.go, internal/storage/csv.go, internal/storage/csv_test.go, internal/storage/json.go, internal/storage/json_test.go, internal/storage/parser.go, internal/storage/parser_test.go, internal/storage/plain.go, internal/storage/plain_test.go, internal/storage/toml.go, internal/storage/toml_test.go, internal/storage/xml.go, internal/storage/xml_test.go, internal/storage/yaml.go, internal/storage/yaml_test.go, node_test.go
=> Add read+write parsers

README.md
Instructions to install are:
```bash
scoop bucket add extras
scoop install dasel
```
=> Add scoop install instructions

README.md, internal/command/root_select_test.go, node_query_multiple.go, node_query_multiple_internal_test.go
=> Add support for key/index selector

README.md, internal/command/put.go, internal/command/root_select_test.go, internal/command/select.go, node_query_multiple_internal_test.go
=> Return null on error

go.mod, go.sum, internal/storage/xml.go, internal/storage/xml_test.go
=> Handle XML entities

CHANGELOG.md, internal/command/put.go, internal/command/put_document_internal.go, internal/command/put_internal_test.go, internal/command/put_object_internal.go, internal/command/root_put_test.go, internal/command/root_select_test.go, internal/command/select.go, internal/storage/csv.go, internal/storage/json.go, internal/storage/json_test.go, internal/storage/option.go, internal/storage/parser.go, internal/storage/parser_test.go, internal/storage/plain.go, internal/storage/toml.go, internal/storage/toml_test.go, internal/storage/xml.go, internal/storage/yaml.go
=> Parser options and compact flag

CHANGELOG.md, internal/storage/csv.go, internal/storage/json.go, internal/storage/json_test.go, internal/storage/yaml.go, internal/storage/yaml_test.go, node.go
=> Update CSV, JSON and YAML parsers to better deal with empty initial documents

CHANGELOG.md, internal/command/root_select_test.go, internal/storage/csv.go
=> Fix a bug that occurred when outputting CSV from JSON

CHANGELOG.md, internal/storage/xml.go, internal/storage/xml_test.go
=> Allow empty XML documents to be parsed

condition_equal.go, condition_more_than.go, condition_test.go, internal/command/root_select_test.go, node_query.go, node_query_internal_test.go, node_query_multiple.go, node_query_multiple_internal_test.go, parse_selector.go
Adds type selector: `[@]`.
Return values are `array`, `map`, `string`, `int`, `float`, `bool`.
=> Add type selector

README.md
With link to the newly created docs.
=> Added Nix to the list of installers

CHANGELOG.md, context.go, internal/command/select_test.go
Fixes https://github.com/TomWright/dasel/issues/314
=> Fix issues with metadata not being preserved through de-referencing

dencoding/yaml_encoder.go, internal/command/put_test.go
Caused by https://github.com/go-yaml/yaml/issues/847
Fixes https://github.com/TomWright/dasel/issues/327
Fixes https://github.com/TomWright/dasel/issues/344
=> Fix an issue that caused yaml strings to be read as numbers

CHANGELOG.md, internal/command/select_test.go, storage/csv.go, storage/csv_test.go
Fixed https://github.com/TomWright/dasel/issues/364
=> Fix an parsing issue in the CSV formatter

CHANGELOG.md, internal/command/select_test.go, value.go
Fixes #392 .
Need to verify that this code is OK to be deleted.
=> Fix a potential panic

storage/csv.go
Fix redundant operations on return values and gofmt
=> Fix redundant operations on return values
