TomWright/dasel

README.md, cmd/dasel/main.go, internal/command/root.go, internal/command/root_test.go
Closes #9 
Adjust `os.Args` to target the select command by default if another command was not targeted.
=> Default to select command

README.md, internal/command/put.go, internal/command/put_bool.go, internal/command/put_document_internal.go, internal/command/put_document_internal_test.go, internal/command/put_int.go, internal/command/put_object_internal.go, internal/command/put_string.go, internal/command/root_put_test.go, node.go, node_propagate.go, node_put.go
- `dasel put document` is now supported.
- Fix an issue in that the read + write flags were ignored in `dasel put object`.
- Fix `dasel put object` command name/description.
- Update command descriptions.
- Fix an issue that stopped you being able to modify the root node.
- Fix some invalid selectors in the README.
=> Add put document support and fix some issues:

.github/workflows/build-dev.yaml, .github/workflows/build.yaml, .github/workflows/test.yaml, CHANGELOG.md, README.md, internal/selfupdate/version.go
This causes the released asset for mac os to be named after `darwin` instead of `macos`. This better resembles the actual architecture and allows users to use `uname` to find the appropriate release.
=> Rename dasel_macos_amd64 to dasel_darwin_amd64

.github/workflows/build-dev.yaml, .github/workflows/build.yaml
https://golang.org/cmd/cgo/
> The cgo tool is enabled by default for native builds on systems where it is expected to work. It is disabled by default when cross-compiling. 
This fact caused linux amd64 builds to build using CGO_ENABLED, and they were therefor dynamically linked: https://github.com/TomWright/dasel/discussions/93
Updating the build command like this should cause all executables to be static.
=> Disable cgo when building binaries

CHANGELOG.md, internal/command/update.go, internal/command/update_stub.go
Small patch to disable the self-updating functionally by introducing a new `noupdater` build tag. The rationale behind this is that having an inclusive command for updating the binary can cause a disparity in versions distributed by package maintainers.
As a sample demonstration when using the build tag:
```shell
% go build -tags noupdater -o dasel cmd/dasel/main.go
% ./dasel
Query and modify data structures using selector strings.
Usage:
dasel [command]
Available Commands:
help        Help about any command
put         Update properties in the given file.
select      Select properties from the given file.
Flags:
-h, --help      help for dasel
-v, --version   version for dasel
Additional help topics:
dasel
Use "dasel [command] --help" for more information about a command.
```
As you can …
=> Optionally disable self-updater

.github/workflows/build-dev.yaml, .github/workflows/build.yaml, docker/alpine.Dockerfile
This would be a much more lightweight image, with the same tool. Furthermore, it will be a lot faster and easier to add extra packages such as `curl` (i.e. a fast and clean `apk add --no-cache curl` instead of a slow `apt-get update && apt-get install curl -y` which adds harder to remove cache.
This does still need you to set up a pipeline to create `ghcr.io/tomwright/dasel:alpine`.
=> ci: alpine Docker image

.github/workflows/build-test.yaml, go.mod, go.sum, internal/storage/xml.go, internal/storage/xml_test.go
This should fix #164 .
Ended up following this comment on mxj:
```
// ------------------- NewMapXml & NewMapXmlReader ... -------------------------
// If XmlCharsetReader != nil, it will be used to decode the XML, if required.
// Note: if CustomDecoder != nil, then XmlCharsetReader is ignored;
// set the CustomDecoder attribute instead.
//   import (
//	     charset "code.google.com/p/go-charset/charset"
//	     github.com/clbanning/mxj
//	 )
//   ...
//   mxj.XmlCharsetReader = charset.NewReader
//   m, merr := mxj.NewMapXml(xmlValue)
var XmlCharsetReader func(charset string, input io.Reader) (io.Reader, error)
```
And so I added a fork to be used inside dasel, as it seems to be pretty complete and a direct port of google code go-charset.
=> xml: add support for other charsets

README.md
The current delete example wasn't using the `-p` flag and was passing an unnecessary value.
=> Fix delete example

CHANGELOG.md, internal/command/root_select_test.go, node.go, node_query_multiple.go, node_query_multiple_internal_test.go, parse_selector.go
Optional Search selectors recursively all the data below the current
node and return all of the results, if at least one result is found.
This is different from standard search, where a search selector must
exist in _all_ documents passed through dasel. The difference with
this selector is that so long as one match is found, dasel will
print the result.
Based on dicussion at https://github.com/TomWright/dasel/discussions/234
=> add optional search selector '(#:<key>=<value>)'

.github/workflows/build-dev.yaml, .github/workflows/build-test.yaml, .github/workflows/build.yaml
Addresses issue #225 by including builds for the darwin arm64 os/arch combo.
I received a M1 MacBook Pro on Friday and have been testing, seems to be working as expected.
=> add darwin amd64 builds

internal/command/root.go
Completion calls `__complete` followed by the text to be completed. The check in `getReadParser` prevents this from working so it must be added to `subCommands` to bypass this check.
=> Add `__complete` to subCommands so that completion works.

error.go, error_test.go
This pull requests adds the `Is(err error) bool` method to the errors.
Errors are hard to distinguish. It is not possible to follow custom logic in case of error.
Take the following code as an example:
```go
func getName(node *dasel.Node) (string, error) {
result, err := node.Query(".Name")
if err != nil {
if errors.Is(err, &dasel.ValueNotFound{}) {
return "", errors.New("name not found")
}
return "", err
}
return result.String(), nil
}
```
Implement the `Is` method so the `errors.Is()` function can be used.
=> Add `Is()` methods for error types.

value.go
fixes #296
It was failing when working on an array which has `null` elements. It is basically caused by trying to set the `reflect.Value` of the `nil` pointer to slice index.
```
panic: reflect: call of reflect.Value.Set on zero Value
goroutine 1 [running]:
reflect.flag.mustBeExportedSlow(0x1517da0?)
reflect/value.go:235 +0xc5
reflect.flag.mustBeExported(...)
reflect/value.go:229
reflect.Value.Set({0x1517da0?, 0xc0002a8620?, 0x7?}, {0x0?, 0x0?, 0xc0002b1790?})
reflect/value.go:2155 +0x9f
github.com/tomwright/dasel/v2.derefSlice({0x1517da0?, 0xc000267cb0?, 0xc0001f4a20?})
github.com/tomwright/dasel/v2/value.go:347 +0x1ad
github.com/tomwright/dasel/v2.deref({0x1517da0?, 0xc000267cb0?, 0x0?})
github.com/tomwright/dasel/v2/value.go:370 +0x65
github.com/tomwright/dasel/v2.derefMap({0x1517da0?, …
```
=> Fixing the error caused by null elements in array

internal/command/select_test.go, value.go
=> Fixes the missing null values in the output

.github/workflows/build-dev.yaml, .github/workflows/build-test.yaml, .github/workflows/build.yaml
Without the `v2` in `github.com/tomwright/dasel/v2/internal.Version` the reference is broken. This leads to all binaries having version number set to `development`.
```bash
$ dasel --version
dasel version development
```
=> Update references to `internal.Version` for v2

CHANGELOG.md, func.go, func_or_default.go, func_or_default_test.go, internal/command/select_test.go
Add a new function `orDefault`.
It takes 2 arguments:
- A selector string
- A selector string that will be used as a fallback
The first selector is expected to return a single value.
The second selector is used if the first causes a NotFound error and is expected to always return a single value.
Example usage:
```bash
$ echo '{
"-LCr5pXw_fN32IqNDr4E": {
"bookCategory": "poetry",
"locale": "en-us",
"mediaType": "book",
"publisher": "Pomelo Books",
"title": "Sound Waves",
"type": "poetry"
},
"-LDDHjkdY0306fZdvhEQ": {
"ISBN13": "978-1534402966",
"bookCategory": "fiction",
"title": "What Can You Do with a Toolbox?",
"type": "picturebook"
}
}' | dasel -r json 'all().mapOf(projectId,key(),title,title,bookCategory,bookCategory,type,type,locale,orDefault(locale,string(unknown)))'
{ …
```
=> orDefault function

CHANGELOG.md, internal/command/delete.go, internal/command/options.go, internal/command/put.go, internal/command/put_test.go, internal/command/select.go, internal/command/select_test.go, storage/csv.go, storage/json.go, storage/option.go, storage/parser.go, storage/plain.go, storage/toml.go, storage/xml.go, storage/yaml.go
Fixes https://github.com/TomWright/dasel/issues/359
=> Add CSV utilities

CHANGELOG.md, func.go, func_null.go, func_null_test.go, func_or_default.go, internal/command/delete_test.go, internal/command/select_test.go, value.go
Fixes https://github.com/TomWright/dasel/issues/346.
Correctly handle null values.
This allows you to select null values as expected, rather then treating them as not found.
=> Handle null values

internal/command/man.go
This makes manpage generation reproducible. I found this problem using Debian's reproducible builds infrastructure.
```diff
--- old/dasel.1	2024-05-02 15:59:19.342436672 -0300
+++ new/dasel.1	2024-05-02 15:52:35.300986397 -0300
@@ -1,5 +1,5 @@
.nh
-.TH "DASEL" "1" "May 2024" "Auto generated by spf13/cobra" ""
+.TH "DASEL" "1" "May 2024" "" ""
.SH NAME
.PP
@@ -73,8 +73,3 @@
.SH SEE ALSO
.PP
\fBdasel-completion(1)\fP, \fBdasel-delete(1)\fP, \fBdasel-man(1)\fP, \fBdasel-put(1)\fP, \fBdasel-validate(1)\fP
-
-
-.SH HISTORY
-.PP
-2-May-2024 Auto generated by spf13/cobra
```
=> Don't include timestamp in generated manpages

CHANGELOG.md, dencoding/yaml.go, dencoding/yaml_decoder.go, dencoding/yaml_decoder_test.go, internal/command/select_test.go
Implements the read capability of #285.
@TomWright this is my first time writing Go. Meaning, I don't mind you nitpicking my code.
=> add support for resolving YAML aliases

dencoding/yaml_decoder.go, dencoding/yaml_decoder_test.go, internal/command/select_test.go
@TomWright my patch in #415 is incorrect and is missing a piece:
1. Regular alias dereferencing, e.g. `foo: *bar` was not handled, only merging an alias into a map.
2. Merging an alias into a map is incorrect in #415 as it should only merge the children of the aliased map rather then the aliased map itself. For example,
```yaml
foo: &foo
bar: 1
baz: "baz"
spam:
<<: *foo
```
currently decodes into
```yaml
foo: &foo
bar: 1
baz: "baz"
spam:
foo: foo
bar: 1
baz: "baz"
```
but should decode into
```yaml
foo: &foo
bar: 1
baz: "baz"
spam:
bar: 1
baz: "baz"
```
=> handle non-merge aliasing

README.md
Use lowercase module name in Go install command.
This fixes the following install issue:
```sh
go: github.com/TomWright/dasel/v3/cmd/dasel@latest: version constraints conflict:
github.com/TomWright/dasel/v3@v3.0.0-20250827120859-ca1aa067eff1: parsing go.mod:
module declares its path as: github.com/tomwright/dasel/v3
but was required as: github.com/TomWright/dasel/v3
```
=> Update install in README.md
